# Generated by Django 5.0 on 2023-12-14 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Denunciante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('data_abertura', models.DateTimeField(verbose_name='data_abertura')),
                ('problema', models.CharField(max_length=200)),
                ('situacao', models.CharField(max_length=200)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.categoria')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.colaborador')),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.denunciante')),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador_Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.chamado')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=8)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.cidade')),
            ],
        ),
        migrations.AddField(
            model_name='chamado',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.endereco'),
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=50)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.endereco')),
            ],
        ),
        migrations.AddField(
            model_name='colaborador',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.instituicao'),
        ),
        migrations.CreateModel(
            name='Instituicao_Contem_Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.categoria')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.instituicao')),
            ],
        ),
    ]
